# Generated by Django 4.2.6 on 2023-11-09 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("unconference", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduletime",
            name="max_sessions",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="schedule_time",
            field=models.ForeignKey(
                limit_choices_to={"allow_sessions": True},
                on_delete=django.db.models.deletion.PROTECT,
                to="unconference.scheduletime",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.UniqueConstraint(
                fields=("schedule_time", "room"), name="unique_booking"
            ),
        ),
    ]
